version: '3'

services:
  backend:
    image: lucianoteles/backend-app:1.0
    ports:
      - "3001:3001"


  frontend:
    image: lucianoteles/frontend-app:1.0
    ports:
      - "3000:3000"
    depends_on:
      - backend
